# Generated by Django 5.0 on 2026-03-02 10:10

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ComponentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('button', 'Button'), ('input', 'Input'), ('card', 'Card'), ('layout', 'Layout'), ('text', 'Text'), ('media', 'Media'), ('form', 'Form'), ('navigation', 'Navigation')], max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('template_data', models.JSONField(default=dict)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'component_templates',
                'ordering': ['-usage_count', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_thumbnails/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='ocr_uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('detected_components', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_analyses', to='api.project')),
            ],
            options={
                'db_table': 'ocr_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('screen_type', models.CharField(choices=[('page', 'Web Page'), ('component', 'Component'), ('modal', 'Modal/Dialog'), ('section', 'Section')], default='page', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=1920)),
                ('height', models.IntegerField(default=1080)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='screen_backgrounds/')),
                ('components', models.JSONField(blank=True, default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='screen_thumbnails/')),
                ('created_from_ocr', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('ocr_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='api.ocranalysis')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='api.project')),
            ],
            options={
                'db_table': 'screens',
                'ordering': ['project', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ScreenVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('components', models.JSONField(blank=True, default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='version_thumbnails/')),
                ('change_type', models.CharField(choices=[('OCR_IMPORT', 'OCR Import'), ('MANUAL_EDIT', 'Manual Edit'), ('AUTO_SAVE', 'Auto Save'), ('RESTORE', 'Restored'), ('DUPLICATE', 'Duplicated')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('changed_components', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_versions', to=settings.AUTH_USER_MODEL)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.screen')),
            ],
            options={
                'db_table': 'screen_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='users_date_jo_b9a773_idx'),
        ),
        migrations.AddIndex(
            model_name='componenttemplate',
            index=models.Index(fields=['category'], name='component_t_categor_b5d63b_idx'),
        ),
        migrations.AddIndex(
            model_name='componenttemplate',
            index=models.Index(fields=['is_active'], name='component_t_is_acti_b22106_idx'),
        ),
        migrations.AddIndex(
            model_name='componenttemplate',
            index=models.Index(fields=['-usage_count'], name='component_t_usage_c_701eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='componenttemplate',
            index=models.Index(fields=['is_system', 'is_public'], name='component_t_is_syst_26cb20_idx'),
        ),
        migrations.AddIndex(
            model_name='componenttemplate',
            index=models.Index(fields=['created_by'], name='component_t_created_8a6dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='projects_owner_i_c299b3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-updated_at'], name='projects_updated_57b80a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='projects_name_3fb8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='ocranalysis',
            index=models.Index(fields=['project'], name='ocr_analyse_project_2ae26f_idx'),
        ),
        migrations.AddIndex(
            model_name='ocranalysis',
            index=models.Index(fields=['-created_at'], name='ocr_analyse_created_0dbe5c_idx'),
        ),
        migrations.AddIndex(
            model_name='ocranalysis',
            index=models.Index(fields=['status'], name='ocr_analyse_status_08b336_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'user'], name='project_mem_project_9e0a06_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user'], name='project_mem_user_id_f59cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['role'], name='project_mem_role_8620a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='screen',
            index=models.Index(fields=['project', 'order'], name='screens_project_e4eef6_idx'),
        ),
        migrations.AddIndex(
            model_name='screen',
            index=models.Index(fields=['-updated_at'], name='screens_updated_a83a37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('project', 'order')},
        ),
        migrations.AddIndex(
            model_name='screenversion',
            index=models.Index(fields=['screen', '-version_number'], name='screen_vers_screen__9aa9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='screenversion',
            index=models.Index(fields=['-created_at'], name='screen_vers_created_13f69f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='screenversion',
            unique_together={('screen', 'version_number')},
        ),
    ]
