# Generated by Django 5.0 on 2026-03-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='screenversion',
            name='changes_delta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='screenversion',
            name='is_base_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='screenversion',
            name='change_type',
            field=models.CharField(choices=[('OCR_IMPORT', 'OCR Import'), ('MANUAL_EDIT', 'Manual Edit'), ('AUTO_SAVE', 'Auto Save'), ('RESTORE', 'Restored'), ('DUPLICATE', 'Duplicated')], default='MANUAL_EDIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='screenversion',
            name='components',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddIndex(
            model_name='screenversion',
            index=models.Index(fields=['screen', 'is_base_version'], name='screen_vers_screen__be951e_idx'),
        ),
    ]
