# Generated by Django 5.0 on 2026-05-21 13:12

import api.models.ocr
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_screenversion_changes_delta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocranalysis',
            name='image',
            field=models.ImageField(upload_to=api.models.ocr.ocr_image_upload_path),
        ),
    ]
